# Theme Github link: https://github.com/korilin/hexo-theme-particle
# Developer: korilin

# html lang
language: zh

# avatar image url
head_img: images/profile.jpg

# home page head info block
head_block_enable: true

# home page head background style.
# If you use a picture as background, you must use the css background-image attribute instead of the background attribute.
# Use image as background ==> home_background: "background-image:url('../home.jpg')"
# Use a color as background ==> home_background: "background: balck"
home_background: "background-image:url('home.jpeg')"

# Particle theme icon is adopts the ant design vue icons
# Link：https://www.antdv.com/components/icon-cn/

# main menu navigation
menu:
  home:
    icon:
      name: home
      theme: filled
    src: /
  about:
    icon:
      name: idcard
      theme: filled
    src: /about # 当你的博客root为 '/' 时
  archives:
    icon:
      name: folder
      theme: filled
    src: /archives
  categories:
    icon:
      name: book
      theme: filled
    src: /categories # 当你的博客root不为 '/'，而是其它时，例如 '/like/'
  tags:
    icon:
      name: tags
      theme: filled
    src: /tags
# side info card
card:
  enable: true
  description: ["一个即将中考的初三仔"]
  icon_links:
    github:
      icon:
        type: antd-icon
        name: github
        theme: filled
        src:
      link: https://github.com/chennuo7967
    twitter:
      icon:
        type: antd-icon
        name: twitter
        theme:
        src:
      link: https://twitter.com/TommyCh23486181
    zhihu:
      icon:
        type: antd-icon
        name: zhihu
        theme:
        src:
      link: https://www.zhihu.com/people/tommy-chen-52-81
    weibo:
      icon:
        type: antd-icon
        name: weibo
        theme:
        src:
      link: https://weibo.com/u/6335774453
  friend_links:
    Github: https://github.com
    Hexo: https://hexo.io

# footer info
footer:
  since: 2023
  # Customize the server domain name ICP
  ICP:
    enable: false
    code: 

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: true
  clientID: fab0ea61b87cb0e8e1e7 # GitHub Application Client ID
  clientSecret: 8be9a35ef72b1480aefb8540a2ea441f10cf3045 # GitHub Application Client Secret
  repo: CommentStore # The name of repository of store comments
  owner: chennuo7967 # GitHub repo owner
  admin: chennuo7967 # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.

# theme style: full / night / maiden, defalut: full
style: full
